apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "flask-lorem-ipsum.fullname" . }}
  labels:
    {{- include "flask-lorem-ipsum.labels" . | nindent 4 }}
spec:
  host: {{ if .Values.route.host }}
        {{ .Values.route.host | quote }}
        {{ else }}
        {{ printf "%s-%s.apps-crc.testing" "flask-lorem-ipsum" .Values.image.tag | quote }}
        {{ end }}
  port:
    targetPort: {{ .Values.route.port.targetPort | default "http" }}
  to:
    kind: Service
    name: {{ include "flask-lorem-ipsum.fullname" . }}
    weight: 100
  wildcardPolicy: None

